#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/anaconda3/lib/python3.6/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/anaconda3/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/Users/Ziad/.config/mearec/1.7.2/cell_models/bbp/mods/x86_64/.libs/libnrnmech.so" "$@"
